language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

script:
    - vendor/bin/phpspec run --format=pretty --no-interaction

jobs:
    include:
        -   stage: Code Quality
            php: 7.3
            env: PHPStan
            install: travis_retry composer install --prefer-dist
            script: vendor/bin/phpstan analyse
